#app.yaml
runtime: python27
api_version: 1
threadsafe: true

handlers:
  - url: /templates
    script: templates
  - url: /stylesheets
    script: stylesheets
  - url: /.*
    script: main.app

libraries:
  - name: jinja2
    version: latest
