runtime: python27
api_version: 1
threadsafe: true

handlers:
  - url: /stylesheets
    static_dir: stylesheets
  - url: /images
    static_dir: images
  - url: /templates
    static_dir: templates
  - url: /.*        # anything I pass in goes to main.app --> a catch all
    script: main.app

libraries:
  - name: jinja2
    version: latest
