runtime: python27
api_version: 1
threadsafe: true

# Get requests goes to to figure out where to go next => with all URLs, go to main.app
handlers:
  - url: /templates
    script: templates
  - url: /.*
    script: main.app

libraries:
  - name: jinja2
    version: latest
  - name: webapp2
    version: latest
